### ISSUE TITLE
Add spam protection

### ISSUE THREAD

**Issue by jjoeldaniel** [EthanThatOneKid/crying-counter#13]
### Issue

Currently, there is no cooldown to the trigger feature. This means you can spam a persons trigger phrase as fast as you want (until Discord rate limits you) which will cause the bot to also spam DM the individual.

### Possible Solution

Take, say, the last 25 messages in a channel. We store the time of the latest message that contains a user trigger in epoch seconds. We then compare this with the time of the current trigger message. If the time is within a specified duration, we ignore the trigger.

**Comment by EthanThatOneKid** [comment]
This is a brilliant idea! Thanks for making an issue.
